//list of words to guess.
exports.newWord = {
  wordList:['OLD FASHIONED','BOURBON','MANHATTAN','PAPPY VAN WINKLE','LONG ISLAND ICED TEA','GUINNESS','BLANTONS','BLOODY MARY','','JOHNNY WALKER','INDIA PALE ALE','WHISKEY SOUR','MACALLAN'],
  hangman: []
};

